In [2]:
import pandas as pd
import numpy as np
from numpy import save
%matplotlib inline

# C | Module Test

<!-- BEGIN QUESTION -->

## Part I&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(10 Points)

In [4]:
# Write your solution here
try:
    f = open('Summaries.txt','x')
    f.write('Alice in Wonderland\n\n')
    f1 = open('Alice.txt','r+')
    x = f1.read()
    f.write(x)
    f1.close()
    f.write("\n\n\n\n\n")
    f.write('Wizard of Oz\n\n')
    f2 = open('Oz.txt','r+')
    y = f2.read()
    f.write(x)
    f2.close()
    f.close()
except:
    pass

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Part II&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(15 Points)

In [27]:
import numpy as np
file=np.load('./numpy_arrays.npz')
arr1,arr2,arr3=file.files
arr1,arr2,arr3=file[arr1],files[arr2],files[arr3]
result_arr=None
# Write your solution here

arr1 = arr1[2::,::]
print(arr1,'\n')
arr2 = arr2[:6:2,11:1:-2]
print(arr2,'\n')
m10= np.array([[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10],[10,10,10,10,10,10,10,10,10,10]])
print(m10.shape)
print(arr3.shape)
print(np.multiply(m10,arr3))
#result_arr = np.subtract(np.add(arr1,np.multiply(m10,arr3)),arr2)
#print(result_arr)

[[22 39 97 21 45]
 [94 40 15 27 82]
 [91 23 67  3 64]] 

[[ 25   9]
 [625  81]] 

(11, 10)
(10, 11)


ValueError: operands could not be broadcast together with shapes (11,10) (10,11) 

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Part III&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(25 Points)

In [46]:
# Write your solution here
import csv
import pandas as pd
df_q1,df_q3,ps_q2,ps_q4 = None,None,None,None
dataFile =  open('cars.csv', 'r')
reader = csv.reader(dataFile)

for row in reader:
    print
    break
df = pd.DataFrame(dataFile,columns =['Car','MPG','Cylinders','Displacement','Horsepower','Weight','Acceleration','Model','Origin'])
print(df.index)

ValueError: Shape of passed values is (406, 1), indices imply (406, 9)

<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Part IV&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(25 Points)

In [ ]:
# Write your solution here
cereal_ratings=None
import json
jstr = '''{"name": ["100% Bran", "100% Natural Bran", "All-Bran", "All-Bran with Extra Fiber", "Almond Delight", "Apple Cinnamon Cheerios", "Apple Jacks", "Basic 4", "Bran Chex", "Bran Flakes", "Cap'n'Crunch", "Cheerios", "Cinnamon Toast Crunch", "Clusters", "Cocoa Puffs", "Corn Chex", "Corn Flakes", "Corn Pops", "Count Chocula", "Cracklin' Oat Bran", "Cream of Wheat (Quick)", "Crispix", "Crispy Wheat & Raisins", "Double Chex", "Froot Loops", "Frosted Flakes", "Frosted Mini-Wheats", "Fruit & Fibre Dates, Walnuts, and Oats", "Fruitful Bran", "Fruity Pebbles", "Golden Crisp", "Golden Grahams", "Grape Nuts Flakes", "Grape-Nuts", "Great Grains Pecan", "Honey Graham Ohs", "Honey Nut Cheerios", "Honey-comb", "Just Right Crunchy  Nuggets", "Just Right Fruit & Nut", "Kix", "Life", "Lucky Charms", "Maypo", "Muesli Raisins, Dates, & Almonds", "Muesli Raisins, Peaches, & Pecans", "Mueslix Crispy Blend", "Multi-Grain Cheerios", "Nut&Honey Crunch", "Nutri-Grain Almond-Raisin", "Nutri-grain Wheat", "Oatmeal Raisin Crisp", "Post Nat. Raisin Bran", "Product 19", "Puffed Rice", "Puffed Wheat", "Quaker Oat Squares", "Quaker Oatmeal", "Raisin Bran", "Raisin Nut Bran", "Raisin Squares", "Rice Chex", "Rice Krispies", "Shredded Wheat", "Shredded Wheat 'n'Bran", "Shredded Wheat spoon size", "Smacks", "Special K", "Strawberry Fruit Wheats", "Total Corn Flakes", "Total Raisin Bran", "Total Whole Grain", "Triples", "Trix", "Wheat Chex", "Wheaties", "Wheaties Honey Gold"], "mfr": ["N", "Q", "K", "K", "R", "G", "K", "G", "R", "P", "Q", "G", "G", "G", "G", "R", "K", "K", "G", "K", "N", "K", "G", "R", "K", "K", "K", "P", "K", "P", "P", "G", "P", "P", "P", "Q", "G", "P", "K", "K", "G", "Q", "G", "A", "R", "R", "K", "G", "K", "K", "K", "G", "P", "K", "Q", "Q", "Q", "Q", "K", "G", "K", "R", "K", "N", "N", "N", "K", "K", "N", "G", "G", "G", "G", "G", "R", "G", "G"], "type": ["C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "H", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "H", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "H", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C", "C"], "calories": ["70", "120", "70", "50", "110", "110", "110", "130", "90", "90", "120", "110", "120", "110", "110", "110", "100", "110", "110", "110", "100", "110", "100", "100", "110", "110", "100", "120", "120", "110", "100", "110", "100", "110", "120", "120", "110", "110", "110", "140", "110", "100", "110", "100", "150", "150", "160", "100", "120", "140", "90", "130", "120", "100", "50", "50", "100", "100", "120", "100", "90", "110", "110", "80", "90", "90", "110", "110", "90", "110", "140", "100", "110", "110", "100", "100", "110"], "protein": ["4", "3", "4", "4", "2", "2", "2", "3", "2", "3", "1", "6", "1", "3", "1", "2", "2", "1", "1", "3", "3", "2", "2", "2", "2", "1", "3", "3", "3", "1", "2", "1", "3", "3", "3", "1", "3", "1", "2", "3", "2", "4", "2", "4", "4", "4", "3", "2", "2", "3", "3", "3", "3", "3", "1", "2", "4", "5", "3", "3", "2", "1", "2", "2", "3", "3", "2", "6", "2", "2", "3", "3", "2", "1", "3", "3", "2"], "fat": ["1", "5", "1", "0", "2", "2", "0", "2", "1", "0", "2", "2", "3", "2", "1", "0", "0", "0", "1", "3", "0", "0", "1", "0", "1", "0", "0", "2", "0", "1", "0", "1", "1", "0", "3", "2", "1", "0", "1", "1", "1", "2", "1", "1", "3", "3", "2", "1", "1", "2", "0", "2", "1", "0", "0", "0", "1", "2", "1", "2", "0", "0", "0", "0", "0", "0", "1", "0", "0", "1", "1", "1", "1", "1", "1", "1", "1"], "sodium": ["130", "15", "260", "140", "200", "180", "125", "210", "200", "210", "220", "290", "210", "140", "180", "280", "290", "90", "180", "140", "80", "220", "140", "190", "125", "200", "0", "160", "240", "135", "45", "280", "140", "170", "75", "220", "250", "180", "170", "170", "260", "150", "180", "0", "95", "150", "150", "220", "190", "220", "170", "170", "200", "320", "0", "0", "135", "0", "210", "140", "0", "240", "290", "0", "0", "0", "70", "230", "15", "200", "190", "200", "250", "140", "230", "200", "200"], "fiber": ["10", "2", "9", "14", "1", "1.5", "1", "2", "4", "5", "0", "2", "0", "2", "0", "0", "1", "1", "0", "4", "1", "1", "2", "1", "1", "1", "3", "5", "5", "0", "0", "0", "3", "3", "3", "1", "1.5", "0", "1", "2", "0", "2", "0", "0", "3", "3", "3", "2", "0", "3", "3", "1.5", "6", "1", "0", "1", "2", "2.7", "5", "2.5", "2", "0", "0", "3", "4", "3", "1", "1", "3", "0", "4", "3", "0", "0", "3", "3", "1"], "carbo": ["5", "8", "7", "8", "14", "10.5", "11", "18", "15", "13", "12", "17", "13", "13", "12", "22", "21", "13", "12", "10", "21", "21", "11", "18", "11", "14", "14", "12", "14", "13", "11", "15", "15", "17", "13", "12", "11.5", "14", "17", "20", "21", "12", "12", "16", "16", "16", "17", "15", "15", "21", "18", "13.5", "11", "20", "13", "10", "14", "-1", "14", "10.5", "15", "23", "22", "16", "19", "20", "9", "16", "15", "21", "15", "16", "21", "13", "17", "17", "16"], "sugars": ["6", "8", "5", "0", "8", "10", "14", "8", "6", "5", "12", "1", "9", "7", "13", "3", "2", "12", "13", "7", "0", "3", "10", "5", "13", "11", "7", "10", "12", "12", "15", "9", "5", "3", "4", "11", "10", "11", "6", "9", "3", "6", "12", "3", "11", "11", "13", "6", "9", "7", "2", "10", "14", "3", "0", "0", "6", "-1", "12", "8", "6", "2", "3", "0", "0", "0", "15", "3", "5", "3", "14", "3", "3", "12", "3", "3", "8"], "potass": ["280", "135", "320", "330", "-1", "70", "30", "100", "125", "190", "35", "105", "45", "105", "55", "25", "35", "20", "65", "160", "-1", "30", "120", "80", "30", "25", "100", "200", "190", "25", "40", "45", "85", "90", "100", "45", "90", "35", "60", "95", "40", "95", "55", "95", "170", "170", "160", "90", "40", "130", "90", "120", "260", "45", "15", "50", "110", "110", "240", "140", "110", "30", "35", "95", "140", "120", "40", "55", "90", "35", "230", "110", "60", "25", "115", "110", "60"], "vitamins": ["25", "0", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "0", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "100", "100", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "25", "100", "0", "0", "25", "0", "25", "25", "25", "25", "25", "0", "0", "0", "25", "25", "25", "100", "100", "100", "25", "25", "25", "25", "25"], "shelf": ["3", "3", "3", "3", "3", "1", "2", "3", "1", "3", "2", "1", "2", "3", "2", "1", "1", "2", "2", "3", "2", "3", "3", "3", "2", "1", "2", "3", "3", "2", "1", "2", "3", "3", "3", "2", "1", "1", "3", "3", "2", "2", "2", "2", "3", "3", "3", "1", "2", "3", "3", "3", "3", "3", "3", "3", "3", "1", "2", "3", "3", "1", "1", "1", "1", "1", "2", "1", "2", "3", "3", "3", "3", "2", "1", "1", "1"], "weight": ["1", "1", "1", "1", "1", "1", "1", "1.33", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1.25", "1.33", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1", "1.3", "1", "1", "1", "1", "1", "1", "1.5", "1", "1", "1.33", "1", "1.25", "1.33", "1", "0.5", "0.5", "1", "1", "1.33", "1", "1", "1", "1", "0.83", "1", "1", "1", "1", "1", "1", "1.5", "1", "1", "1", "1", "1", "1"], "cups": ["0.33", "1", "0.33", "0.5", "0.75", "0.75", "1", "0.75", "0.67", "0.67", "0.75", "1.25", "0.75", "0.5", "1", "1", "1", "1", "1", "0.5", "1", "1", "0.75", "0.75", "1", "0.75", "0.8", "0.67", "0.67", "0.75", "0.88", "0.75", "0.88", "0.25", "0.33", "1", "0.75", "1.33", "1", "0.75", "1.5", "0.67", "1", "1", "1", "1", "0.67", "1", "0.67", "0.67", "1", "0.5", "0.67", "1", "1", "1", "0.5", "0.67", "0.75", "0.5", "0.5", "1.13", "1", "1", "0.67", "0.67", "0.75", "1", "1", "1", "1", "1", "0.75", "1", "0.67", "1", "0.75"], "rating": ["68.402973", "33.983679", "59.425505", "93.704912", "34.384843", "29.509541", "33.174094", "37.038562", "49.120253", "53.313813", "18.042851", "50.764999", "19.823573", "40.400208", "22.736446", "41.445019", "45.863324", "35.782791", "22.396513", "40.448772", "64.533816", "46.895644", "36.176196", "44.330856", "32.207582", "31.435973", "58.345141", "40.917047", "41.015492", "28.025765", "35.252444", "23.804043", "52.076897", "53.371007", "45.811716", "21.871292", "31.072217", "28.742414", "36.523683", "36.471512", "39.241114", "45.328074", "26.734515", "54.850917", "37.136863", "34.139765", "30.313351", "40.105965", "29.924285", "40.692320", "59.642837", "30.450843", "37.840594", "41.503540", "60.756112", "63.005645", "49.511874", "50.828392", "39.259197", "39.703400", "55.333142", "41.998933", "40.560159", "68.235885", "74.472949", "72.801787", "31.230054", "53.131324", "59.363993", "38.839746", "28.592785", "46.658844", "39.106174", "27.753301", "49.787445", "51.592193", "36.187559"]}'''
jdata = json.loads(jstr)
print(jdata)

<!-- END QUESTION -->



<!-- END QUESTION -->

<!-- BEGIN QUESTION -->

## Part V&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;(20 Points)

In [53]:
Cities=['Melbourne','Adelaide','Canberra','Sydney','Perth']#List to store city names
StoreCost=[250,230,250,320,200]#List to store cost of 
print("Welcome Guest. Please choose the city where you want to reserve a room")
i=1
#for city in Cities:
for i, city in enumerate(Cities):
    print(i,' ',city,': Cost per day of stay',StoreCost[i-1],'AUD')
    #i+=1
BookCity=input('Enter the number corresponding to the city you would like to book')#selected city
Days=input('Enter the number of days you would like to book for')#selcted duration
d=0 #discount set to 0 
if (int(Days)>=7 and int(BookCity)!=4):
    d=0.05
elif (int(BookCity)==5):
    d=0.1
else: pass
print('You have selected to stay at',Cities[int(BookCity)-1],'for',Days,'days')
if(d>0):
    print("You get a discount")
print('Your total cost is',StoreCost[int(BookCity)-1]*int(Days)*(1-d),'AUD')

Welcome Guest. Please choose the city where you want to reserve a room
0   Melbourne : Cost per day of stay 200 AUD
1   Adelaide : Cost per day of stay 250 AUD
2   Canberra : Cost per day of stay 230 AUD
3   Sydney : Cost per day of stay 250 AUD
4   Perth : Cost per day of stay 320 AUD
Enter the number corresponding to the city you would like to book1
Enter the number of days you would like to book for20
You have selected to stay at Melbourne for 20 days
You get a discount
Your total cost is 4750.0 AUD
